set -g default-terminal "tmux-256color"

set -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
bind-key -T copy-mode-vi v send-keys -X begin-selection
set -g base-index 1
unbind C-b
set -g prefix M-j
bind -n M-j send-prefix

set -s escape-time 0
set -g repeat-time 0



set -g status-right ''


# Inactive windows (dark gray background, light gray text)
set -g window-status-format "#[fg=colour254,bg=colour235] #I: #W #[default]"

# Active window (blue background, white text, bold)
set -g window-status-current-format "#[fg=black,bg=#ffffff] #I: #W #[bg=#ffffff]"
# Separators between windows
set -g window-status-separator '#[bg=default]  '

